name: 'xcresulttool'
description: 'generates a human-readable test report from the Xcode result bundle and shows it on GitHub Checks.'
author: 'kishikawa katsumi'
inputs:
  path:
    required: true
    description: 'Path to the xcresult bundle'
  token:
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
  title:
    description: 'Title for the check results'
    default: 'Xcode test results'
  show_passed_tests:
    description: 'Show passed tests'
    default: true
  show_code_coverage:
    description: 'Whether to show code coverage'
    default: true
  upload_bundles:
    description: 'Whether to upload the xcresult bundles. possible values: always, failure, never. Specifying failure will only upload the bundle if all the tests do not pass.'
    default: always
  delete_merged_results:
    description: 'If using merged results, delete the merged result bundle after processing'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'blue'
